version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: api_trade_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-api_trade_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/ddl.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    container_name: api_trade_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: